/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectosuc;

import EDD.ArchivoSuc;
import EDD.ListaDoblementeLigada;
import EDD.NodoLista;
import EDD.Sucursales;
import ioarchico.lsarchivo;
import java.io.IOException;
import java.util.LinkedList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author danchita45
 */
public class AltaSuc extends javax.swing.JFrame {

    /**
     * Creates new form AltaSuc
     */
    public AltaSuc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        noSuctxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreSuctxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        zonatxt = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("No. Sucursal");

        noSuctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSuctxtActionPerformed(evt);
            }
        });
        noSuctxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noSuctxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noSuctxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noSuctxtKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre ");

        nombreSuctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSuctxtActionPerformed(evt);
            }
        });
        nombreSuctxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreSuctxtKeyReleased(evt);
            }
        });

        jLabel3.setText("Zona");

        zonatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonatxtActionPerformed(evt);
            }
        });
        zonatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zonatxtKeyReleased(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreSuctxt, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(noSuctxt)
                            .addComponent(zonatxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noSuctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreSuctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zonatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noSuctxtActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_noSuctxtActionPerformed
    {//GEN-HEADEREND:event_noSuctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noSuctxtActionPerformed

    private void nombreSuctxtActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombreSuctxtActionPerformed
    {//GEN-HEADEREND:event_nombreSuctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSuctxtActionPerformed

    private void zonatxtActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_zonatxtActionPerformed
    {//GEN-HEADEREND:event_zonatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zonatxtActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GuardarActionPerformed
    {//GEN-HEADEREND:event_GuardarActionPerformed

        if (VerificarCampos()) {
            lsarchivo archivo = new lsarchivo();

            ListaDoblementeLigada sucs = archivo.SacaDatos();
            if (sucs == null) {
                sucs = new ListaDoblementeLigada();
            }
            NodoLista nuevonodo = new NodoLista();
            Sucursales newsuc = new Sucursales();
            newsuc.setNoSuc(Integer.parseInt(noSuctxt.getText()));
            newsuc.setNombre(nombreSuctxt.getText());
            newsuc.setZona(Integer.parseInt(zonatxt.getText()));
            nuevonodo.setEtiqueta(Integer.toString(newsuc.getNoSuc()));
            nuevonodo.setTObj(newsuc);
            sucs.inserta(nuevonodo);
            try {
                archivo.InsertarnuevaLista(sucs);
            } catch (IOException ex) {
                Logger.getLogger(AltaSuc.class.getName()).log(Level.SEVERE, null, ex);
            }
            MenuPrinc menu = new MenuPrinc();
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuPrinc a = new MenuPrinc();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void noSuctxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noSuctxtKeyTyped

    }//GEN-LAST:event_noSuctxtKeyTyped

    private void noSuctxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noSuctxtKeyPressed

    }//GEN-LAST:event_noSuctxtKeyPressed

    private void noSuctxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noSuctxtKeyReleased
        if (!noSuctxt.getText().matches("[0-9]{1,3}")) {
            JOptionPane.showMessageDialog(this, "Este Campo solo Acepta Numeros");
            noSuctxt.setText("");
        }
    }//GEN-LAST:event_noSuctxtKeyReleased

    private void nombreSuctxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreSuctxtKeyReleased
        if (!nombreSuctxt.getText().matches("[a-zA-Z]*")) {
            JOptionPane.showMessageDialog(this, "Este Campo solo Acepta Letras");
            nombreSuctxt.setText("");
        }
    }//GEN-LAST:event_nombreSuctxtKeyReleased

    private void zonatxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zonatxtKeyReleased
        if (!noSuctxt.getText().matches("[0-9]{1,3}")) {
            JOptionPane.showMessageDialog(this, "Este Campo solo Acepta Numeros");
            noSuctxt.setText("");
        }
    }//GEN-LAST:event_zonatxtKeyReleased

    public boolean VerificarCampos() {
        if (noSuctxt.getText() != "" && nombreSuctxt.getText() != "" && zonatxt.getText() != "") {
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Verifique todos los campos ");
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaSuc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField noSuctxt;
    private javax.swing.JTextField nombreSuctxt;
    private javax.swing.JTextField zonatxt;
    // End of variables declaration//GEN-END:variables
}
