/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectosuc;

import EDD.ArchivoSuc;
import EDD.IngresoEgreso;
import EDD.ListaDoblementeLigada;
import EDD.NodoLista;
import EDD.Sucursales;
import ioarchico.lsarchivo;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.io.Serializable;
import java.util.LinkedList;
import java.util.Set;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author danchita45
 */
public class MenuPrinc extends javax.swing.JFrame implements Serializable {

    private Sucursales sucs;

    /**
     * Creates new form MenuPrinc
     */
    public MenuPrinc() {
        initComponents();

        lsarchivo nuevo = new lsarchivo();

        ListaDoblementeLigada nl = nuevo.SacaDatos();
        if (nl != null) {
            DefaultTableModel dt = new DefaultTableModel(new String[]{"No.Sucursal", "Nombre", "Zona"}, nl.count());
            jTableSucs.setModel(dt);
            TableModel modeldata = jTableSucs.getModel();
            NodoLista nodoSuc = nl.getr();
            int i = 0;
            while (i < nl.count()) {
                Sucursales sucr = (Sucursales) nodoSuc.getTObj();
                modeldata.setValueAt(sucr.getNoSuc(), i, 0);
                modeldata.setValueAt(sucr.getNombre(), i, 1);
                modeldata.setValueAt(sucr.getZona(), i, 2);
                nodoSuc = nodoSuc.getSig();
                i++;
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSucs = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        altaSuc = new javax.swing.JMenu();
        bajaSuc = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        consultaGeneral = new javax.swing.JMenu();
        consultaEspecifica = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jTableSucs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No. Sucursal", "Nombre", "Zona"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableSucs);
        if (jTableSucs.getColumnModel().getColumnCount() > 0) {
            jTableSucs.getColumnModel().getColumn(0).setResizable(false);
            jTableSucs.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("VaciarBD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        altaSuc.setText("Alta Sucursal");
        altaSuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                altaSucMouseClicked(evt);
            }
        });
        jMenuBar1.add(altaSuc);

        bajaSuc.setText("Baja Sucursal");
        bajaSuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bajaSucMouseClicked(evt);
            }
        });
        jMenuBar1.add(bajaSuc);

        jMenu3.setText("Modificar Sucursal");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        consultaGeneral.setText("Consulta General");
        consultaGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaGeneralMouseClicked(evt);
            }
        });
        jMenuBar1.add(consultaGeneral);

        consultaEspecifica.setText("Consulta Especifica(Zona)");
        consultaEspecifica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaEspecificaMouseClicked(evt);
            }
        });
        jMenuBar1.add(consultaEspecifica);

        jMenu2.setText("Registrar I/E");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void altaSucMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_altaSucMouseClicked
    {//GEN-HEADEREND:event_altaSucMouseClicked
        AltaSuc suc = new AltaSuc();
        suc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_altaSucMouseClicked

    private void bajaSucMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaSucMouseClicked
    {//GEN-HEADEREND:event_bajaSucMouseClicked
        BajaSuc b = new BajaSuc();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bajaSucMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuPrinc m = new MenuPrinc();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        RegistrarIE r = new RegistrarIE();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void consultaGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaGeneralMouseClicked
        IngresosEgresos v = new IngresosEgresos();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultaGeneralMouseClicked

    private void consultaEspecificaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaEspecificaMouseClicked
        SumaZonasGeneral s = new SumaZonasGeneral();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultaEspecificaMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        ModificarSuc a = new ModificarSuc();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int op = JOptionPane.showConfirmDialog(this, "¿Está Seguro de Eliminar TODOS los Datos?");

        if (op == JOptionPane.YES_OPTION) {
            File arch = new File("listas.dat");
            RandomAccessFile archivorw = null;
            try {
                archivorw = new RandomAccessFile(arch, "rw");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MenuPrinc.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                archivorw.setLength(0);
            } catch (IOException ex) {
                Logger.getLogger(MenuPrinc.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu altaSuc;
    private javax.swing.JMenu bajaSuc;
    private javax.swing.JMenu consultaEspecifica;
    private javax.swing.JMenu consultaGeneral;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSucs;
    // End of variables declaration//GEN-END:variables
}
