/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectosuc;

import EDD.ListaDoblementeLigada;
import EDD.NodoLista;
import EDD.Sucursales;
import ioarchico.lsarchivo;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Danchita45
 */
public class ModificarSuc extends javax.swing.JFrame {

    /**
     * Creates new form ModificarSuc
     */
    public ModificarSuc() {
        initComponents();

        llenarCombox();
        llenarCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Guardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        noSuctxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreSuctxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        zonatxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ComboSucursal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("No. Sucursal");

        noSuctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSuctxtActionPerformed(evt);
            }
        });
        noSuctxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noSuctxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noSuctxtKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre ");

        nombreSuctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSuctxtActionPerformed(evt);
            }
        });
        nombreSuctxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreSuctxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreSuctxtKeyTyped(evt);
            }
        });

        jLabel3.setText("Zona");

        zonatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonatxtActionPerformed(evt);
            }
        });
        zonatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zonatxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zonatxtKeyTyped(evt);
            }
        });

        jLabel4.setText("Sucursal:");

        ComboSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboSucursal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboSucursalItemStateChanged(evt);
            }
        });
        ComboSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSucursalActionPerformed(evt);
            }
        });
        ComboSucursal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ComboSucursalPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(noSuctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(nombreSuctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(zonatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(ComboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noSuctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreSuctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zonatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(ComboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        if (VerificarCampos()) {
            lsarchivo archivo = new lsarchivo();
            ListaDoblementeLigada ldl = archivo.SacaDatos();
            
            
            NodoLista nodo = ldl.eliminar((String) ComboSucursal.getSelectedItem());
            Sucursales SucPallenar = (Sucursales) nodo.getTObj();

            SucPallenar.setNoSuc(Integer.parseInt(noSuctxt.getText()));
            SucPallenar.setNombre(nombreSuctxt.getText());
            SucPallenar.setZona(Integer.parseInt(zonatxt.getText()));

            nodo.setEtiqueta(Integer.toString(SucPallenar.getNoSuc()));
            nodo.setTObj(SucPallenar);
            
            
            ldl.inserta(nodo);
            try {
                archivo.InsertarnuevaLista(ldl);
            } catch (IOException ex) {
                Logger.getLogger(AltaSuc.class.getName()).log(Level.SEVERE, null, ex);
            }
            MenuPrinc menu = new MenuPrinc();
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_GuardarActionPerformed
    public boolean VerificarCampos() {
        if (noSuctxt.getText() != "" && nombreSuctxt.getText() != "" && zonatxt.getText() != "") {
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Verifique todos los campos ");
            return false;
        }
    }

    public void llenarCombox() {
        ComboSucursal.removeAllItems();
        lsarchivo nuevo = new lsarchivo();
        ListaDoblementeLigada nl = nuevo.SacaDatos();
        NodoLista nodoSuc = nl.getr();
        int i = 0;
        while (i < nl.count()) {
            Sucursales sucr = (Sucursales) nodoSuc.getTObj();
            ComboSucursal.addItem(Integer.toString(sucr.getNoSuc()));
            nodoSuc = nodoSuc.getSig();
            i++;
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuPrinc a = new MenuPrinc();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    private void noSuctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSuctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noSuctxtActionPerformed

    private void nombreSuctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSuctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSuctxtActionPerformed

    private void zonatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zonatxtActionPerformed

    private void ComboSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSucursalActionPerformed

    }//GEN-LAST:event_ComboSucursalActionPerformed


    private void ComboSucursalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ComboSucursalPropertyChange

    }//GEN-LAST:event_ComboSucursalPropertyChange

    private void ComboSucursalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboSucursalItemStateChanged

        lsarchivo archivo = new lsarchivo();
        ListaDoblementeLigada ldl = archivo.SacaDatos();
        NodoLista nodo = ldl.buscar((String) ComboSucursal.getSelectedItem());
        if (nodo != null) {
            Sucursales SucPallenar = (Sucursales) nodo.getTObj();
            noSuctxt.setText(Integer.toString(SucPallenar.getNoSuc()));
            nombreSuctxt.setText(SucPallenar.getNombre());
            zonatxt.setText(Integer.toString(SucPallenar.getZona()));
        }


    }//GEN-LAST:event_ComboSucursalItemStateChanged

    private void noSuctxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noSuctxtKeyTyped
        if (!noSuctxt.getText().matches("[0-9]{1,3}")) {
            JOptionPane.showMessageDialog(this, "Este Campo solo Acepta Numeros");
            noSuctxt.setText("");
        }
    }//GEN-LAST:event_noSuctxtKeyTyped

    private void noSuctxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noSuctxtKeyReleased

    }//GEN-LAST:event_noSuctxtKeyReleased

    private void nombreSuctxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreSuctxtKeyReleased

    }//GEN-LAST:event_nombreSuctxtKeyReleased

    private void zonatxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zonatxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_zonatxtKeyReleased

    private void nombreSuctxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreSuctxtKeyTyped
        if (!nombreSuctxt.getText().matches("[a-zA-Z]*")) {
            JOptionPane.showMessageDialog(this, "Este Campo solo Acepta Numeros");
            nombreSuctxt.setText("");
        }        
    }//GEN-LAST:event_nombreSuctxtKeyTyped

    private void zonatxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zonatxtKeyTyped
          if (!zonatxt.getText().matches("[0-9]{1,3}")) {
            JOptionPane.showMessageDialog(this, "Este Campo solo Acepta Numeros");
            zonatxt.setText("");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_zonatxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarSuc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboSucursal;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField noSuctxt;
    private javax.swing.JTextField nombreSuctxt;
    private javax.swing.JTextField zonatxt;
    // End of variables declaration//GEN-END:variables

    private void llenarCampos() {

        lsarchivo archivo = new lsarchivo();
        ListaDoblementeLigada ldl = archivo.SacaDatos();
        NodoLista nodo = ldl.buscar((String) ComboSucursal.getSelectedItem());
        Sucursales SucPallenar = (Sucursales) nodo.getTObj();
        noSuctxt.setText(Integer.toString(SucPallenar.getNoSuc()));
        nombreSuctxt.setText(SucPallenar.getNombre());
        zonatxt.setText(Integer.toString(SucPallenar.getZona()));
    }
}
