/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectosuc;

import EDD.ArchivoSuc;
import EDD.IngresoEgreso;
import EDD.ListaDoblementeLigada;
import EDD.NodoLista;
import EDD.Sucursales;
import ioarchico.lsarchivo;
import java.io.IOException;
import java.util.LinkedList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Danchita45
 */
public class RegistrarIE extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarIE
     */
    public RegistrarIE() {
        initComponents();
        llenarCombox();
    }

    public boolean verificarCampos() {
        if (montotxt.getText() != "" && descuentotxt.getText() != "" && fechatxt.getText() != "") {
            return true;
        } else {
            return false;
        }
    }

    public void llenarCombox() {
        ComboSucursal.removeAllItems();
        ComboIE.removeAllItems();
        lsarchivo nuevo = new lsarchivo();

        ListaDoblementeLigada nl = nuevo.SacaDatos();

        ComboIE.addItem("Ingreso");
        ComboIE.addItem("Egreso");
        NodoLista nodoSuc = nl.getr();
        int i = 0;
        while (i < nl.count()) {
            Sucursales sucr = (Sucursales) nodoSuc.getTObj();
            ComboSucursal.addItem(Integer.toString(sucr.getNoSuc()));
            nodoSuc = nodoSuc.getSig();
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboSucursal = new javax.swing.JComboBox<>();
        ComboIE = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechatxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        montotxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        descuentotxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Sucursal:");

        ComboSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSucursalActionPerformed(evt);
            }
        });

        ComboIE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Ingreso/ Egreso:");

        jLabel3.setText("Monto:");

        fechatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechatxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha (dd/MM/yyyy):");

        montotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montotxtActionPerformed(evt);
            }
        });
        montotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                montotxtKeyReleased(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        descuentotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descuentotxtActionPerformed(evt);
            }
        });
        descuentotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descuentotxtKeyReleased(evt);
            }
        });

        jLabel5.setText("Descuento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descuentotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ComboIE, 0, 161, Short.MAX_VALUE)
                                .addComponent(ComboSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(montotxt, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(105, 105, 105))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(237, 237, 237)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(montotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descuentotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(305, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(121, 121, 121)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fechatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechatxtActionPerformed

    private void montotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montotxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuPrinc m = new MenuPrinc();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            lsarchivo archivo = new lsarchivo();
            ListaDoblementeLigada ldl = archivo.SacaDatos();
            NodoLista CINodo = new NodoLista();
            NodoLista nodo = ldl.eliminar((String) ComboSucursal.getSelectedItem());

            Sucursales succomodin = (Sucursales) nodo.getTObj();
            ListaDoblementeLigada CI = (ListaDoblementeLigada) succomodin.getcI();
            ListaDoblementeLigada CE = (ListaDoblementeLigada) succomodin.getcE();

            if (CI == null) {
                CI = new ListaDoblementeLigada();
            }
            if (CE == null) {
                CE = new ListaDoblementeLigada();
            }

            String IE = (String) ComboIE.getSelectedItem();
            IngresoEgreso nuevoEgreso = new IngresoEgreso();

            if (IE == "Ingreso") {

                nuevoEgreso.setDescuento(Double.parseDouble(descuentotxt.getText()));
                if (nuevoEgreso.getDescuento() != 0.0) {
                    double descuentopercent = Double.parseDouble(descuentotxt.getText()) / 100;
                    double Montopercent = Double.parseDouble(montotxt.getText());
                    double total = Montopercent - (descuentopercent * Montopercent);
                    nuevoEgreso.setMonto(total);
                } else {
                    nuevoEgreso.setMonto(Double.parseDouble(montotxt.getText()));
                }
                nuevoEgreso.setFecha(fechatxt.getText());
                nuevoEgreso.setSucursal(Integer.parseInt((String) ComboSucursal.getSelectedItem()));
                nuevoEgreso.setEI(1);

                CINodo.setEtiqueta("Ingreso");
                CINodo.setTObj(nuevoEgreso);
                CI.inserta(CINodo);
                succomodin.setcI(CI);
                nodo.setTObj(succomodin);
                ldl.inserta(nodo);

            } else {
                nuevoEgreso.setDescuento(Double.parseDouble(descuentotxt.getText()));
                if (nuevoEgreso.getDescuento() != 0.0) {
                    double descuentopercent = Double.parseDouble(descuentotxt.getText()) / 100;
                    double Montopercent = Double.parseDouble(montotxt.getText());
                    double total = Montopercent - (descuentopercent * Montopercent);
                    nuevoEgreso.setMonto(total);
                } else {
                    nuevoEgreso.setMonto(Double.parseDouble(montotxt.getText()));
                }
                nuevoEgreso.setFecha(fechatxt.getText());
                nuevoEgreso.setSucursal(Integer.parseInt((String) ComboSucursal.getSelectedItem()));
                nuevoEgreso.setEI(0);

                CINodo.setEtiqueta("Egreso");
                CINodo.setTObj(nuevoEgreso);
                CE.inserta(CINodo);
                succomodin.setcE(CE);
                nodo.setTObj(succomodin);
                ldl.inserta(nodo);
            }
            archivo.InsertarnuevaLista(ldl);
            MenuPrinc m = new MenuPrinc();
            m.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(RegistrarIE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ComboSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSucursalActionPerformed

    private void descuentotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descuentotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descuentotxtActionPerformed

    private void montotxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montotxtKeyReleased
        
        if (!montotxt.getText().matches("[0-9]{1,5}")) {
            JOptionPane.showMessageDialog(this, "Este Campo solo Acepta Numeros(para este campo solo 5 digitos)");
            montotxt.setText("");
        }
    }//GEN-LAST:event_montotxtKeyReleased

    private void descuentotxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descuentotxtKeyReleased
        if (!descuentotxt.getText().matches("[0-9]{1,3}")) {
            JOptionPane.showMessageDialog(this, "Este Campo solo Acepta Numeros");
            descuentotxt.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_descuentotxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarIE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboIE;
    private javax.swing.JComboBox<String> ComboSucursal;
    private javax.swing.JTextField descuentotxt;
    private javax.swing.JTextField fechatxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField montotxt;
    // End of variables declaration//GEN-END:variables
}
